// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tuanchill/lofola-api/internal/controller"
	"github.com/tuanchill/lofola-api/internal/repo"
	"github.com/tuanchill/lofola-api/internal/repo/redis"
	"github.com/tuanchill/lofola-api/internal/service"
)

// Injectors from auth.wire.go:

func InitAuthRouterHandler() (*controller.AuthController, error) {
	iUserRepo := repo.NewUserRepo()
	iOtpRedisRepo := redis.NewOtpRedisRepo()
	iTokenRedisRepo := redis.NewTokenRedisRepo()
	iAuthService := service.NewAuthService(iUserRepo, iOtpRedisRepo, iTokenRedisRepo)
	authController := controller.NewAuthController(iAuthService)
	return authController, nil
}

// Injectors from group.wire.go:

func InitGroupRouterHandler() (*controller.GroupController, error) {
	iGroupRepo := repo.NewGroupRepo()
	iUserRepo := repo.NewUserRepo()
	iGroupService := service.NewGroupService(iGroupRepo, iUserRepo)
	groupController := controller.NewGroupController(iGroupService)
	return groupController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepo := repo.NewUserRepo()
	iUserService := service.NewUserService(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
