server:
  port: 8080

mongodb:
  uri: mongodb://localhost:27017
  database: mydb

mysql:
  uri: mysql://localhost:3306
  database: mydb

redis:
  uri: redis://localhost:6379
  database: 0

sercurity:
  jwt:
    secret: mysecret
